export const FUGLE_REALTIME_HTTP_CLIENT = Symbol('FUGLE_REALTIME_HTTP_CLIENT');
export const FUGLE_REALTIME_WEBSOCKET_CLIENT = Symbol('FUGLE_REALTIME_WEBSOCKET_CLIENT');
export const FUGLE_REALTIME_CLIENT_OPTIONS = Symbol('FUGLE_REALTIME_CLIENT_OPTIONS');
